name: NitroX-Zenith Kernel Build

on:
  push:
    branches:
      - Nitro-X-KSU
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "Nitro-X-KSU"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 📥 Checkout Source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 1

      - name: ⚡ Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 2G

      - name: 🧰 Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl zip bc bison flex \
          libssl-dev libelf-dev ccache build-essential python3

      - name: 🛠 Make Build Script Executable
        run: chmod +x build.sh

      - name: 🕒 Set KBUILD Variables
        run: |
          echo "KBUILD_BUILD_USER=JOD_BUNNY" >> $GITHUB_ENV
          echo "KBUILD_BUILD_HOST=BUNNY-X" >> $GITHUB_ENV
          echo "KBUILD_BUILD_TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: 🚀 Build Kernel
        env:
          KBUILD_BUILD_USER: ${{ env.KBUILD_BUILD_USER }}
          KBUILD_BUILD_HOST: ${{ env.KBUILD_BUILD_HOST }}
          KBUILD_BUILD_TIMESTAMP: ${{ env.KBUILD_BUILD_TIMESTAMP }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: ./build.sh

      - name: 📦 Upload Build Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: NitroX-Zenith-KSU-Kernel
          path: |
             *.zip
             AnyKernel3/*.zip
             out/arch/arm64/boot/Image*
