name: HyperFusionX - Ultra (KSUN) Kernel Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 📥 Checkout Source
        uses: actions/checkout@v4
        with:
           ref: ${{ github.event.inputs.branch }}

      - name: 🧰 Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git curl zip bc bison flex \
            libssl-dev libelf-dev \
            ccache build-essential

      - name: 🛠 Make Build Script Executable
        run: chmod +x build.sh

      - name: 🚀 Run Kernel Build
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: ./build.sh

      - name: 📦 Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HyperFusionX-Kernel
          path: ~/AnyKernel3/*.zip
